version: '3.6'

services:
  db:
    command: --log-bin=master --binlog-format=row
    container_name: mariadb
    image: mariadb:10.4.4-bionic
    restart: always
    ports:
      - "33104:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - maria:/var/lib/mysql
      - ./database/:/docker-entrypoint-initdb.d/

  producer:
    command: --dbAddress db:3306
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer
    image: producer
    depends_on:
      - db
      - maxwell
    restart: always

  maxwell:
    container_name: maxwell
    image: zendesk/maxwell
    depends_on:
      - db
      - kafka
    command: ./bin/maxwell --user=root --password=example --host=db --producer=kafka --log_level=error --kafka.bootstrap.servers=kafka:9092 --kafka_topic=maxwell

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper
  
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "maxwell:1:1"
    container_name: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.socks

volumes:
  maria: